config/routes.rb
Terminology::Application.routes.draw do
  resources :concepts

  resources :groups

  resources :codes

  resources :codesets

  resources :issuers

  resources :countries

  resources :media_types

  resources :languages

  resources :identifiers

  root to: 'concepts#index', as: 'root'

end

app/models/issuer.rb
class Issuer < ActiveRecord::Base
  attr_accessible :name
  has_many :codesets
end

app/controllers/issuers_controller.rb
class IssuersController < ApplicationController
  # GET /issuers
  # GET /issuers.json
  def index
    @issuers = Issuer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issuers }
    end
  end

  # GET /issuers/1
  # GET /issuers/1.json
  def show
    @issuer = Issuer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issuer }
    end
  end

  # GET /issuers/new
  # GET /issuers/new.json
  def new
    @issuer = Issuer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issuer }
    end
  end

  # GET /issuers/1/edit
  def edit
    @issuer = Issuer.find(params[:id])
  end

  # POST /issuers
  # POST /issuers.json
  def create
    @issuer = Issuer.new(params[:issuer])

    respond_to do |format|
      if @issuer.save
        format.html { redirect_to @issuer, notice: 'Issuer was successfully created.' }
        format.json { render json: @issuer, status: :created, location: @issuer }
      else
        format.html { render action: "new" }
        format.json { render json: @issuer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /issuers/1
  # PUT /issuers/1.json
  def update
    @issuer = Issuer.find(params[:id])

    respond_to do |format|
      if @issuer.update_attributes(params[:issuer])
        format.html { redirect_to @issuer, notice: 'Issuer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @issuer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issuers/1
  # DELETE /issuers/1.json
  def destroy
    @issuer = Issuer.find(params[:id])
    @issuer.destroy

    respond_to do |format|
      format.html { redirect_to issuers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/issuers_helper.rb
module IssuersHelper
end

app/views/issuers/_form.html.erb
<%= form_for(@issuer) do |f| %>
  <% if @issuer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issuer.errors.count, "error") %> prohibited this issuer from being saved:</h2>

      <ul>
      <% @issuer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issuers/edit.html.erb
<h1>Editing issuer</h1>

<%= render 'form' %>

<%= link_to 'Show', @issuer %> |
<%= link_to 'Back', issuers_path %>

app/views/issuers/index.html.erb
<h1>Listing issuers</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @issuers.each do |issuer| %>
  <tr>
    <td><%= issuer.name %></td>
    <td><%= link_to 'Show', issuer %></td>
    <td><%= link_to 'Edit', edit_issuer_path(issuer) %></td>
    <td><%= link_to 'Destroy', issuer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Issuer', new_issuer_path %>

app/views/issuers/new.html.erb
<h1>New issuer</h1>

<%= render 'form' %>

<%= link_to 'Back', issuers_path %>

app/views/issuers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @issuer.name %>
</p>


<%= link_to 'Edit', edit_issuer_path(@issuer) %> |
<%= link_to 'Back', issuers_path %>