config/routes.rb
Terminology::Application.routes.draw do
  resources :concepts

  resources :groups

  resources :codes

  resources :codesets

  resources :issuers

  resources :countries

  resources :media_types

  resources :languages

  resources :identifiers

  root to: 'concepts#index', as: 'root'

end

app/models/code.rb
class Code < ActiveRecord::Base
  attr_accessible :codeset_id, :value
  belongs_to :codeset
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  # GET /codes
  # GET /codes.json
  def index
    @codes = Code.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @codes }
    end
  end

  # GET /codes/1
  # GET /codes/1.json
  def show
    @code = Code.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @code }
    end
  end

  # GET /codes/new
  # GET /codes/new.json
  def new
    @code = Code.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @code }
    end
  end

  # GET /codes/1/edit
  def edit
    @code = Code.find(params[:id])
  end

  # POST /codes
  # POST /codes.json
  def create
    @code = Code.new(params[:code])

    respond_to do |format|
      if @code.save
        format.html { redirect_to @code, notice: 'Code was successfully created.' }
        format.json { render json: @code, status: :created, location: @code }
      else
        format.html { render action: "new" }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /codes/1
  # PUT /codes/1.json
  def update
    @code = Code.find(params[:id])

    respond_to do |format|
      if @code.update_attributes(params[:code])
        format.html { redirect_to @code, notice: 'Code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /codes/1
  # DELETE /codes/1.json
  def destroy
    @code = Code.find(params[:id])
    @code.destroy

    respond_to do |format|
      format.html { redirect_to codes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/views/codes/_form.html.erb
<%= form_for(@code) do |f| %>
  <% if @code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@code.errors.count, "error") %> prohibited this code from being saved:</h2>

      <ul>
      <% @code.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codeset_id %><br />
    <%= f.number_field :codeset_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/codes/edit.html.erb
<h1>Editing code</h1>

<%= render 'form' %>

<%= link_to 'Show', @code %> |
<%= link_to 'Back', codes_path %>

app/views/codes/index.html.erb
<h1>Listing codes</h1>

<table>
  <tr>
    <th>Codeset</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @codes.each do |code| %>
  <tr>
    <td><%= code.codeset.openehr_id %></td>
    <td><%= code.value %></td>
    <td><%= link_to 'Show', code %></td>
    <td><%= link_to 'Edit', edit_code_path(code) %></td>
    <td><%= link_to 'Destroy', code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Code', new_code_path %>

app/views/codes/new.html.erb
<h1>New code</h1>

<%= render 'form' %>

<%= link_to 'Back', codes_path %>

app/views/codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codeset:</b>
  <%= @code.codeset_id %>
</p>

<p>
  <b>Value:</b>
  <%= @code.value %>
</p>


<%= link_to 'Edit', edit_code_path(@code) %> |
<%= link_to 'Back', codes_path %>