config/routes.rb
Terminology::Application.routes.draw do
  resources :concepts

  resources :groups

  resources :codes

  resources :codesets

  resources :issuers

  resources :countries

  resources :media_types

  resources :languages

  resources :identifiers

  root to: 'concepts#index', as: 'root'

end

app/models/concept.rb
class Concept < ActiveRecord::Base
  attr_accessible :code, :group_id, :integer, :rubric
  belongs_to :group
end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
  # GET /concepts
  # GET /concepts.json
  def index
    @concepts = Concept.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @concepts }
    end
  end

  # GET /concepts/1
  # GET /concepts/1.json
  def show
    @concept = Concept.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @concept }
    end
  end

  # GET /concepts/new
  # GET /concepts/new.json
  def new
    @concept = Concept.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @concept }
    end
  end

  # GET /concepts/1/edit
  def edit
    @concept = Concept.find(params[:id])
  end

  # POST /concepts
  # POST /concepts.json
  def create
    @concept = Concept.new(params[:concept])

    respond_to do |format|
      if @concept.save
        format.html { redirect_to @concept, notice: 'Concept was successfully created.' }
        format.json { render json: @concept, status: :created, location: @concept }
      else
        format.html { render action: "new" }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /concepts/1
  # PUT /concepts/1.json
  def update
    @concept = Concept.find(params[:id])

    respond_to do |format|
      if @concept.update_attributes(params[:concept])
        format.html { redirect_to @concept, notice: 'Concept was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concepts/1
  # DELETE /concepts/1.json
  def destroy
    @concept = Concept.find(params[:id])
    @concept.destroy

    respond_to do |format|
      format.html { redirect_to concepts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/views/concepts/_form.html.erb
<%= form_for(@concept) do |f| %>
  <% if @concept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concept.errors.count, "error") %> prohibited this concept from being saved:</h2>

      <ul>
      <% @concept.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.text_field :group_id %>
  </div>
  <div class="field">
    <%= f.label :integer %><br />
    <%= f.text_field :integer %>
  </div>
  <div class="field">
    <%= f.label :rubric %><br />
    <%= f.text_field :rubric %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/concepts/edit.html.erb
<h1>Editing concept</h1>

<%= render 'form' %>

<%= link_to 'Show', @concept %> |
<%= link_to 'Back', concepts_path %>

app/views/concepts/index.html.erb
<h1>Listing concepts</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Rubric</th>
    <th>Group</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @concepts.each do |concept| %>
  <tr>
    <td><%= concept.code %></td>
    <td><%= concept.rubric %></td>
    <td><%= concept.group.name %></td>
    <td><%= link_to 'Show', concept %></td>
    <td><%= link_to 'Edit', edit_concept_path(concept) %></td>
    <td><%= link_to 'Destroy', concept, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Concept', new_concept_path %>

app/views/concepts/new.html.erb
<h1>New concept</h1>

<%= render 'form' %>

<%= link_to 'Back', concepts_path %>

app/views/concepts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @concept.code %>
</p>

<p>
  <b>Group:</b>
  <%= @concept.group_id %>
</p>

<p>
  <b>Integer:</b>
  <%= @concept.integer %>
</p>

<p>
  <b>Rubric:</b>
  <%= @concept.rubric %>
</p>


<%= link_to 'Edit', edit_concept_path(@concept) %> |
<%= link_to 'Back', concepts_path %>